### ISSUE TITLE
Artifact system?

### ISSUE THREAD

**Issue by timholy** [mlewe/BlossomV.jl#16]
It would be nice to update this package to more modern Julia. Specifically, it would be nice to generate a Project.toml file, and especially nice to use the artifact system (Julia 1.3+). There is a wizard for generating the build: https://github.com/JuliaPackaging/BinaryBuilder.jl. I played with it briefly and it seemed fairly straightforward, but the first hurdle is figuring out how to handle your customizations (`sharedlib.patch` and `interface/`).

**Comment by mlewe** [comment]
It's been a while since I have done anything with Julia, but I will take a look at how package metadata is handled nowadays.

Regarding BinaryBuilder: I'm sorry, but that's out of the question, given the license of the software. I realize that people don't really read the license notice in the README, but I'm not sure how to make it more obvious.

It would really be best if somebody sat down with the original paper and wrote a pure Julia implementation of the algorithm, so that we can throw away this package.

**Comment by mlewe** [comment]
A new version has been released, which contains a `Project.toml` and should run under any recent version of Julia.

Using the artifact system is out of the question, therefore I'm closing this issue.

**Comment by timholy** [comment]
Thanks @mlewe, and thanks for explaining that the license makes the Artifact impossible. Maybe I (or someone) will get around to an open-licensed implementation in pure Julia.
