### ISSUE TITLE
tag a new version and integration with LightGraphs

### ISSUE THREAD

**Issue by CarloLucibello** [mlewe/BlossomV.jl#7]
Hi, 
I'm integrating this package with LightGraphs, if you don't mind. Can you tag a new version?

Bye,
Carlo

**Comment by mlewe** [comment]
Tagged as v0.1.0.

**Comment by CarloLucibello** [comment]
Thanks! crossref  JuliaGraphs/LightGraphsExtras.jl#16

**Comment by CarloLucibello** [comment]
do you have any clue for this failure? 

https://travis-ci.org/JuliaGraphs/LightGraphsExtras.jl/builds/161020164

why the c++1y flag?

**Comment by mlewe** [comment]
You're pulling in BlossomV v0.0.3 (because JuliaLang/METADATA.jl#6407 is not merged yet).
That version requires C++14 support, which is not present for gcc version 4.6 provided in the Ubuntu 12.04 environment on travis.

Wait for the pull request to be merged, and maybe also require a minimum version of v0.1 for BlossomV.

This issue will be closed automatically as soon as the pull-request gets merged.
